# Generated by Django 5.0.1 on 2024-02-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reusable', models.BooleanField()),
                ('Non-renewable energy MJ', models.FloatField()),
                ('Global warming potential KG', models.FloatField()),
                ('Blue water KG', models.FloatField()),
                ('Solid waste at hospital KG', models.FloatField()),
            ],
        ),
    ]
