# Generated by Django 5.0.1 on 2024-02-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gown',
            old_name='Non-renewable energy MJ',
            new_name='nre_emissions',
        ),
    ]
