# Generated by Django 5.0.3 on 2025-03-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gown',
            name='session_key',
        ),
    ]
