# Generated by Django 5.0.1 on 2024-03-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_rename_non_renewable_energy_mj_gown_nre_emissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gown',
            old_name='Blue water KG',
            new_name='blue_water',
        ),
        migrations.RenameField(
            model_name='gown',
            old_name='Global warming potential KG',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='gown',
            old_name='Solid waste at hospital KG',
            new_name='solid_waste',
        ),
    ]
