# Generated by Django 5.0.3 on 2024-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0003_rename_blue_water_kg_gown_blue_water_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gown",
            name="cost",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
