# Generated by Django 5.0.3 on 2024-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0005_gown_certificates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="gown",
            name="certificates",
        ),
        migrations.AddField(
            model_name="gown",
            name="certificates",
            field=models.ManyToManyField(blank=True, to="emissions.certification"),
        ),
    ]
