# Generated by Django 5.0.3 on 2024-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0006_certification_remove_gown_certificates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="description",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
