# Generated by Django 5.0.3 on 2024-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0007_certification_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="description",
            field=models.CharField(max_length=2555),
        ),
    ]
