# Generated by Django 5.0.3 on 2024-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0008_alter_certification_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="gown",
            name="washes",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
