# Generated by Django 5.0.3 on 2024-07-01 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0009_gown_washes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emission_stage",
                    models.CharField(
                        choices=[
                            ("Co2", "kg CO2 eq"),
                            ("ENERGY", "Energy use in MJ"),
                            ("WATER", "Water consumption in Liters"),
                        ],
                        max_length=255,
                    ),
                ),
                ("fibers", models.FloatField()),
                ("yarn_production", models.FloatField()),
                ("fabric_production", models.FloatField()),
                ("finishing", models.FloatField()),
                ("manufacturing", models.FloatField()),
                ("packaging", models.FloatField()),
                ("transport", models.FloatField()),
                ("use", models.FloatField()),
                (
                    "gown",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emissions.gown"
                    ),
                ),
            ],
        ),
    ]
