# Generated by Django 5.0.3 on 2024-07-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0010_emissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gown",
            name="blue_water",
        ),
        migrations.RemoveField(
            model_name="gown",
            name="co2",
        ),
        migrations.RemoveField(
            model_name="gown",
            name="nre_emissions",
        ),
        migrations.RemoveField(
            model_name="gown",
            name="solid_waste",
        ),
    ]
