# Generated by Django 5.0.3 on 2024-07-06 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0012_gown_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="gown",
            name="comfort",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="0 - comofort is not included in the optimization."
                    ),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
    ]
