# Generated by Django 5.0.3 on 2024-07-08 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0013_gown_comfort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gown",
            name="certificates",
            field=models.ManyToManyField(
                blank=True,
                to="emissions.certification",
                verbose_name="Sustainability certificates",
            ),
        ),
        migrations.AlterField(
            model_name="gown",
            name="comfort",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="0 - comofort is not included in the optimization."
                    ),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Comfort level (likert scale)",
            ),
        ),
        migrations.AlterField(
            model_name="gown",
            name="cost",
            field=models.FloatField(verbose_name="Cost per piece"),
        ),
        migrations.AlterField(
            model_name="gown",
            name="weight",
            field=models.FloatField(verbose_name="Weight in grams"),
        ),
    ]
