# Generated by Django 5.0.3 on 2024-07-08 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0015_alter_gown_comfort"),
    ]

    operations = [
        migrations.AddField(
            model_name="gown",
            name="hygine",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="0 - hygine is not included in the optimization."
                    ),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Hygine level (likert scale)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gown",
            name="comfort",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="0 - comofort is not included in the optimization."
                    ),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Comfort level (likert scale)",
            ),
        ),
    ]
