# Generated by Django 5.0.3 on 2024-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0016_gown_hygine_alter_gown_comfort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envpar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Environmental Parameter',
                'verbose_name_plural': 'Environmental Parameters',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_per_week', models.IntegerField()),
                ('pickups_per_week', models.IntegerField()),
                ('loss_percentage', models.FloatField(default=0.001)),
                ('optimizer', models.ManyToManyField(to='emissions.envpar')),
            ],
        ),
    ]
