# Generated by Django 5.0.3 on 2024-10-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0017_envpar_stages_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='stages',
            field=models.ManyToManyField(to='emissions.stages'),
        ),
    ]
