# Generated by Django 5.0.3 on 2024-11-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0018_specification_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='optimizer',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='stages',
        ),
        migrations.DeleteModel(
            name='Envpar',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
    ]
