# Generated by Django 5.0.3 on 2024-11-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0019_remove_specification_optimizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='emission_stage',
            field=models.CharField(choices=[('CO2', 'kg CO2 eq'), ('ENERGY', 'Energy use in MJ'), ('WATER', 'Water consumption in Liters')], max_length=255),
        ),
    ]
