# Generated by Django 5.0.3 on 2024-12-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0020_alter_emissions_emission_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='emission_stage',
            field=models.CharField(choices=[('CO2', 'kg CO2 eq'), ('ENERGY', 'Energy use in MJ'), ('WATER', 'Water consumption in Liters'), ('COST', 'Water consumption in Liters')], max_length=255),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='fabric_production',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='fibers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='finishing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='manufacturing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='packaging',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='transport',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='use',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissions',
            name='yarn_production',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
