# Generated by Django 5.0.3 on 2024-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0021_alter_emissions_emission_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissions',
            name='eol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissions',
            name='lost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gown',
            name='source',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissions',
            name='emission_stage',
            field=models.CharField(choices=[('CO2', 'kg CO2 eq'), ('Energy', 'Energy use in MJ'), ('Water', 'Water consumption in Liters'), ('Cost', 'Cost')], max_length=255),
        ),
    ]
