# Generated by Django 5.0.3 on 2024-12-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0022_emissions_eol_emissions_lost_gown_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissions',
            old_name='manufacturing',
            new_name='production',
        ),
    ]
