# Generated by Django 5.0.3 on 2024-12-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0023_rename_manufacturing_emissions_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='gown',
            name='laundry_cost',
            field=models.FloatField(default=0, verbose_name='Cost per wash'),
            preserve_default=False,
        ),
    ]
