# Generated by Django 5.0.3 on 2025-01-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0024_gown_laundry_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost per piece'),
        ),
        migrations.AlterField(
            model_name='gown',
            name='laundry_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost per wash'),
        ),
        migrations.AlterField(
            model_name='gown',
            name='washes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gown',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight in grams'),
        ),
    ]
