# Generated by Django 5.0.3 on 2025-01-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0025_alter_gown_cost_alter_gown_laundry_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(),
        ),
    ]
