# Generated by Django 5.0.3 on 2025-01-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0026_alter_certification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissions',
            name='emission_stage',
            field=models.CharField(choices=[('CO2', 'kg CO2 eq'), ('Energy', 'Energy use in MJ'), ('Water', 'Water consumption in Liters'), ('Cost', 'Cost'), ('FTE', 'Local FTE')], max_length=255),
        ),
    ]
