# Generated by Django 5.0.3 on 2025-01-18 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0027_alter_emissions_emission_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost per piece €'),
        ),
        migrations.AlterField(
            model_name='gown',
            name='hygine',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='0 - hygine is not included in the optimization.'), django.core.validators.MaxValueValidator(6, message='6 - Not applicable')], verbose_name='Hygine level (likert scale)'),
        ),
        migrations.AlterField(
            model_name='gown',
            name='laundry_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost per wash €'),
        ),
    ]
