# Generated by Django 5.0.3 on 2025-01-18 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0028_alter_gown_cost_alter_gown_hygine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='comfort',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='0 - comofort is not included in the optimization.'), django.core.validators.MaxValueValidator(6, message='6 - Not applicable')], verbose_name='Comfort level (likert scale)'),
        ),
    ]
