# Generated by Django 5.0.3 on 2025-01-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0029_alter_gown_comfort'),
    ]

    operations = [
        migrations.AddField(
            model_name='gown',
            name='fte_local',
            field=models.FloatField(blank=True, null=True, verbose_name='Local FTE'),
        ),
        migrations.AddField(
            model_name='gown',
            name='fte_local_extra',
            field=models.FloatField(blank=True, null=True, verbose_name='Local FTE-extra'),
        ),
        migrations.AddField(
            model_name='gown',
            name='type',
            field=models.CharField(choices=[('Bio', 'Bio'), ('Recycled', 'Recycled'), ('Regular', 'Regular')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gown',
            name='woven',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissions',
            name='emission_stage',
            field=models.CharField(choices=[('CO2', 'kg CO2 eq'), ('Energy', 'Energy use in MJ'), ('Water', 'Water consumption in Liters'), ('Cost', 'Cost'), ('RECIPE', 'RECIPE score')], max_length=255),
        ),
    ]
