# Generated by Django 5.0.3 on 2025-01-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0030_gown_fte_local_gown_fte_local_extra_gown_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gown',
            name='visible',
            field=models.BooleanField(default=True, help_text='Indicates if the gown is visible on the front-end.'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmissionsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_stage', models.CharField(choices=[('Production', 'Production'), ('Use', 'Use phase'), ('Lost', 'Lost'), ('EOL', 'End Of life')], max_length=255)),
                ('emission_substage', models.CharField(choices=[('Total', 'Total emissions'), ('Raw', 'Raw'), ('Advanced', 'Advanced'), ('Transport', 'Transport')], max_length=255)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('co2', models.CharField(blank=True, max_length=255, null=True)),
                ('energy', models.CharField(blank=True, max_length=255, null=True)),
                ('water', models.CharField(blank=True, max_length=255, null=True)),
                ('recipe', models.CharField(blank=True, max_length=255, null=True)),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.gown')),
            ],
        ),
    ]
