# Generated by Django 5.0.3 on 2025-01-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0031_gown_visible_emissionsnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='gown',
            name='residual_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Residual value €'),
        ),
        migrations.AddField(
            model_name='gown',
            name='waste_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Waste cost penalty €'),
        ),
    ]
