# Generated by Django 5.0.3 on 2025-01-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0032_gown_residual_value_gown_waste_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsnew',
            name='emission_stage',
            field=models.CharField(choices=[('Production', 'Production'), ('Use', 'Use phase'), ('LOST', 'Lost'), ('EOL', 'End Of life')], max_length=255),
        ),
    ]
