# Generated by Django 5.0.3 on 2025-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0033_alter_emissionsnew_emission_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='woven',
            field=models.BooleanField(blank=True),
        ),
    ]
