# Generated by Django 5.0.3 on 2025-01-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0034_alter_gown_woven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='woven',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
