# Generated by Django 5.0.3 on 2025-01-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0035_alter_gown_woven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='visible',
            field=models.BooleanField(blank=True, help_text='Indicates if the gown is visible on the front-end.', null=True),
        ),
    ]
