# Generated by Django 5.0.3 on 2025-02-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0037_alter_emissionsnew_co2_alter_emissionsnew_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsnew',
            name='emission_stage',
            field=models.CharField(choices=[('Production', 'Production'), ('Use', 'Use phase'), ('LOST', 'Lost'), ('EOL', 'End Of life')], max_length=255),
        ),
        migrations.AlterField(
            model_name='emissionsnew',
            name='emission_substage',
            field=models.CharField(choices=[('Total', 'Total emissions'), ('Raw', 'Raw'), ('Advanced', 'Advanced'), ('Transport', 'Transport')], max_length=255),
        ),
    ]
