# Generated by Django 5.0.1 on 2024-02-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gown name', models.CharField(max_length=100)),
                ('reusable', models.BooleanField()),
                ('times_reused', models.IntegerField(blank=True)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_1', models.CharField(max_length=100)),
                ('component_1_percent', models.FloatField()),
                ('component_2', models.CharField(blank=True, max_length=100)),
                ('component_2_percent', models.FloatField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recycled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Method of transportation', models.CharField(blank=True, max_length=100)),
                ('tonnage', models.IntegerField(blank=True)),
                ('fuel', models.CharField(blank=True, choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('LNG', 'Liquefied natural gas'), ('ELECTR', 'Electric')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoveringMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_reused', models.IntegerField(blank=True, null=True)),
                ('surface', models.FloatField()),
                ('weight', models.FloatField()),
                ('adhisive_edge', models.CharField(blank=True, choices=[('LPE', 'Loose polyester edge'), ('LPEE', 'Loose polyesterene edge'), ('FIXED', 'Fixed edge')], max_length=100)),
                ('Gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
                ('materials', models.ManyToManyField(related_name='materials_coveringmaterials', to='dashboard.material')),
            ],
        ),
        migrations.AddField(
            model_name='gown',
            name='materials_v1',
            field=models.ManyToManyField(related_name='materials_v1', to='dashboard.material'),
        ),
        migrations.AddField(
            model_name='gown',
            name='materials_v2',
            field=models.ManyToManyField(blank=True, related_name='materials_v2', to='dashboard.material'),
        ),
        migrations.CreateModel(
            name='LaundryTransportPackagingGown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('Gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
                ('material', models.ManyToManyField(related_name='laundry_transport_packaging_gown', to='dashboard.packagingmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryPackagingCoveringMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('covering_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coveringmaterial')),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
                ('material', models.ManyToManyField(to='dashboard.packagingmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPackagingCoveringMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_weight', models.IntegerField()),
                ('primary_quantity', models.IntegerField()),
                ('secondary_weight', models.IntegerField(blank=True, null=True)),
                ('secondary_quantity', models.IntegerField(blank=True, null=True)),
                ('covering_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.coveringmaterial')),
                ('primary_material', models.ManyToManyField(related_name='production_packaging_covering_material_primary', to='dashboard.packagingmaterial')),
                ('secondary_material', models.ManyToManyField(blank=True, related_name='production_packaging_covering_material_secondary', to='dashboard.packagingmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPackagingGown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_weight', models.IntegerField()),
                ('primary_quantity', models.IntegerField()),
                ('secondary_weight', models.IntegerField(blank=True)),
                ('secondary_quantity', models.IntegerField(blank=True)),
                ('Gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
                ('primary_material', models.ManyToManyField(related_name='production_packaging_gown_primary_material', to='dashboard.packagingmaterial')),
                ('secondary_material', models.ManyToManyField(blank=True, related_name='production_packaging_gown_secondary_material', to='dashboard.packagingmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='SingleUseUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat', models.FloatField()),
                ('electrical_efficiency', models.IntegerField()),
                ('thermal_efficiency', models.IntegerField()),
                ('electricity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.electricity')),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
            ],
        ),
        migrations.CreateModel(
            name='SterilizationInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_gas', models.FloatField()),
                ('ethylene_oxide', models.FloatField(blank=True)),
                ('nitrogen', models.FloatField()),
                ('water', models.FloatField()),
                ('electricity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.electricity')),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
            ],
        ),
        migrations.CreateModel(
            name='SterilizationToHospitalPackagingCoveringMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covering_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coveringmaterial')),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
                ('material', models.ManyToManyField(related_name='sterilization_to_hospital_covering_material_packaging', to='dashboard.packagingmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='SterilizationToHospitalPackagingGown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterilization_paper', models.BooleanField(blank=True)),
                ('primary_weight', models.IntegerField()),
                ('primary_quantity', models.IntegerField()),
                ('secondary_weight', models.IntegerField(blank=True, null=True)),
                ('secondary_quantity', models.IntegerField(blank=True, null=True)),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown', verbose_name='Gown')),
                ('primary_material', models.ManyToManyField(related_name='primary_material', to='dashboard.packagingmaterial')),
                ('secondary_material', models.ManyToManyField(blank=True, related_name='secondary_material', to='dashboard.packagingmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='TransportHospitalToWashingGown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.transportmethod')),
            ],
        ),
        migrations.CreateModel(
            name='TransportToNetherlands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country of origin', models.CharField(blank=True, max_length=100)),
                ('distance_1', models.IntegerField()),
                ('distance_2', models.IntegerField()),
                ('covering_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coveringmaterial')),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
                ('transport_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transport_to_netherlands_1', to='dashboard.transportmethod')),
                ('transport_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transport_to_netherlands_2', to='dashboard.transportmethod')),
            ],
        ),
        migrations.CreateModel(
            name='WashingInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_gas', models.FloatField()),
                ('water', models.FloatField()),
                ('demineralized_water', models.FloatField()),
                ('detergent', models.FloatField()),
                ('electricity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.electricity')),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
            ],
        ),
    ]
