# Generated by Django 5.0.1 on 2024-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='component_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='component_2_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
