# Generated by Django 5.0.1 on 2024-02-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_material_component_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gown',
            old_name='Gown name',
            new_name='name',
        ),
    ]
