# Generated by Django 5.0.1 on 2024-02-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_gown_times_reused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coveringmaterial',
            old_name='Gown',
            new_name='gown',
        ),
    ]
