# Generated by Django 5.0.1 on 2024-02-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_gown_coveringmaterial_gown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='component_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='component_1_percent',
            field=models.FloatField(null=True),
        ),
    ]
