# Generated by Django 5.0.1 on 2024-02-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_material_component_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='component_1_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
