# Generated by Django 5.0.1 on 2024-02-06 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_material_component_1_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrypackagingcoveringmaterial',
            name='covering_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coveringmaterial'),
        ),
        migrations.AlterField(
            model_name='productionpackaginggown',
            name='primary_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionpackaginggown',
            name='primary_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionpackaginggown',
            name='secondary_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionpackaginggown',
            name='secondary_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sterilizationinputs',
            name='ethylene_oxide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportmethod',
            name='Method of transportation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportmethod',
            name='fuel',
            field=models.CharField(blank=True, choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('LNG', 'Liquefied natural gas'), ('ELECTR', 'Electric')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportmethod',
            name='tonnage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporttonetherlands',
            name='distance_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporttonetherlands',
            name='distance_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporttonetherlands',
            name='transport_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transport_to_netherlands_2', to='dashboard.transportmethod'),
        ),
    ]
