# Generated by Django 5.0.1 on 2024-02-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_laundrypackagingcoveringmaterial_covering_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundrytransportpackaginggown',
            old_name='Gown',
            new_name='gown',
        ),
        migrations.RenameField(
            model_name='productionpackaginggown',
            old_name='Gown',
            new_name='gown',
        ),
        migrations.RenameField(
            model_name='transportmethod',
            old_name='Method of transportation',
            new_name='transport',
        ),
        migrations.RenameField(
            model_name='transporttonetherlands',
            old_name='Country of origin',
            new_name='country_of_origin',
        ),
    ]
