# Generated by Django 5.0.1 on 2024-02-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_gown_laundrytransportpackaginggown_gown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporttonetherlands',
            name='transport_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transport_to_netherlands_1', to='dashboard.transportmethod'),
        ),
        migrations.AlterField(
            model_name='transporttonetherlands',
            name='transport_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transport_to_netherlands_2', to='dashboard.transportmethod'),
        ),
    ]
