# Generated by Django 5.0.1 on 2024-02-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_transporttonetherlands_transport_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covering_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.coveringmaterial')),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gown')),
            ],
        ),
    ]
